# Generated by Django 4.0.3 on 2022-04-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('dueDate', models.DateField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('roll', models.CharField(max_length=200)),
            ],
        ),
    ]
